/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.sudip.avro;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface Avro5 {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"Avro5\",\"namespace\":\"com.sudip.avro\",\"types\":[{\"type\":\"record\",\"name\":\"ApplicationInstance\",\"fields\":[{\"name\":\"id\",\"type\":\"string\"},{\"name\":\"eventTime\",\"type\":\"long\"}]},{\"type\":\"record\",\"name\":\"ModuleInstance\",\"fields\":[{\"name\":\"id\",\"type\":\"string\"},{\"name\":\"eventTime\",\"type\":\"long\"},{\"name\":\"parentApp\",\"type\":\"ApplicationInstance\"}]},{\"type\":\"record\",\"name\":\"ScreenInstance\",\"fields\":[{\"name\":\"id\",\"type\":\"string\"},{\"name\":\"eventTime\",\"type\":\"long\"},{\"name\":\"parentModule\",\"type\":\"ModuleInstance\"}]}],\"messages\":{}}");

  @SuppressWarnings("all")
  public interface Callback extends Avro5 {
    public static final org.apache.avro.Protocol PROTOCOL = com.sudip.avro.Avro5.PROTOCOL;
  }
}